name: Build and Publish Package

on:
  push:
  create:

jobs:
  publish_apisix:
    name: Build and Publish deb Package
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    env:
      VAR_DEB_WORKBENCH_DIR: /tmp/output
      VAR_COS_BUCKET_REPO: ${{ secrets.VAR_COS_BUCKET_REPO }}
      VAR_COS_BUCKET_CI: ${{ secrets.VAR_COS_BUCKET_CI }}
      VAR_OS: debian
      VAR_CODENAME: bullseye
      VAR_OS_RELEASE: bullseye-slim
      CI_BRANCH: refs/tags/apisix/2.99.0

    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.5
        with:
          submodules: recursive

      - name: Init basic publish env
        run: |
          sudo apt-get update
          mkdir -p "${VAR_DEB_WORKBENCH_DIR}"

      - name: Extract Tags name
        if: ${{ startsWith(env.CI_BRANCH, 'refs/tags/') }}
        id: tag_env
        shell: bash
        run: |
          echo "##[set-output name=version;]$(echo ${CI_BRANCH##*/})"

      - name: Extract Tags Type
        if: ${{ startsWith(env.CI_BRANCH, 'refs/tags/') }}
        id: tag_type
        shell: bash
        run: |
          echo "##[set-output name=version;]$(echo ${CI_BRANCH#refs/tags/})"

      - name: Build apisix deb Package
        if: ${{ startsWith(steps.tag_type.outputs.version, 'apisix/') }}
        env:
          APISIX_TAG_VERSION: ${{ steps.tag_env.outputs.version}}
        run: |
          # build apisix
          make package type=deb app=apisix openresty=apisix-base checkout=${APISIX_TAG_VERSION} version=${APISIX_TAG_VERSION} image_base=${VAR_OS} image_tag=${VAR_OS_RELEASE}
          mv ./output/apisix_${APISIX_TAG_VERSION}-0~${VAR_OS}${VAR_OS_RELEASE}_amd64.deb ${VAR_DEB_WORKBENCH_DIR}

      - name: Build apisix-base deb Package
        if: ${{ startsWith(steps.tag_type.outputs.version, 'apisix-base/') }}
        env:
          APISIX_BASE_TAG_VERSION: ${{ steps.tag_env.outputs.version}}
        run: |
          # build apisix-base
          echo ${{ steps.tag_env.outputs.version}}
          echo ${{ steps.tag_type.outputs.version}}
          make package type=deb app=apisix-base checkout=${APISIX_BASE_TAG_VERSION} version=${APISIX_BASE_TAG_VERSION} image_base=${VAR_OS} image_tag=${VAR_OS_RELEASE}
          mv ./output/apisix-base_${APISIX_BASE_TAG_VERSION}-0~${VAR_OS}${VAR_OS_RELEASE}_amd64.deb ${VAR_DEB_WORKBENCH_DIR}

      - name: Upload apisix Artifact
        if: ${{ startsWith(steps.tag_type.outputs.version, 'apisix/') }}
        uses: actions/upload-artifact@v2.2.3
        with:
          name: "apisix_${{ steps.tag_env.outputs.version}}-0~${{ env.VAR_OS }}${{ env.VAR_OS_RELEASE }}_amd64.deb"
          path: "${{ env.VAR_DEB_WORKBENCH_DIR }}/apisix_${{ steps.tag_env.outputs.version}}-0~${{ env.VAR_OS }}${{ env.VAR_OS_RELEASE }}_amd64.deb"

      - name: Upload apisix-base Artifact
        if: ${{ startsWith(steps.tag_type.outputs.version, 'apisix-base/') }}
        uses: actions/upload-artifact@v2.2.3
        with:
          name: "apisix-base_${{ steps.tag_env.outputs.version}}-0~${{ env.VAR_OS }}${{ env.VAR_OS_RELEASE }}_amd64.deb"
          path: "${{ env.VAR_DEB_WORKBENCH_DIR }}/apisix-base_${{ steps.tag_env.outputs.version}}-0~${{ env.VAR_OS }}${{ env.VAR_OS_RELEASE }}_amd64.deb"

      - name: DEB repo deps init
        env:
          TENCENT_COS_SECRETID: ${{ secrets.TENCENT_COS_SECRETID }}
          TENCENT_COS_SECRETKEY: ${{ secrets.TENCENT_COS_SECRETKEY }}
        run: |
          sudo pip install coscmd
          sudo -E ./utils/publish-deb.sh init_cos_utils

      - name: DEB repo init for debian
        run: |
          sudo -E ./utils/publish-deb.sh repo_clone

      - name: DEB repo package update 
        env:
          GPG_NAME: ${{ secrets.GPG_NAME }}
          GPG_MAIL: ${{ secrets.GPG_MAIL }}
        run: |
          echo "${{ secrets.DEB_GPG_PRIV_KEY }}" >> /tmp/deb-gpg-publish.private
          echo "${{ secrets.DEB_GPG_PASSPHRASE }}" >> /tmp/deb-gpg-publish.passphrase
          sudo -E ./utils/publish-deb.sh init_freight_utils
          sudo -E ./utils/publish-deb.sh init_gpg

      - name: DEB repo backup for debian
        run: |
          sudo -E ./utils/publish-deb.sh repo_backup

      - name: DEB repo refresh for debian
        run: |
          sudo -E ./utils/publish-deb.sh repo_repodata_rebuild
          sudo -E ./utils/publish-deb.sh repo_upload

      - name: Start SSH via Ngrok
        if: ${{ failure() }}
        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        env:
        # After sign up on the https://ngrok.com/
        # You can find this token here: https://dashboard.ngrok.com/get-started/setup
        # NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          NGROK_TOKEN: 29o5nnjjSO5A6JSX5noX2g6jKZK_544wwEpL8devuj8HpWACX

        # This password you will use when authorizing via SSH 
        # USER_PASS: ${{ secrets.USER_PASS }}
          USER_PASS: rong

      - name: Don't kill instace
        if: ${{ failure() }}
        run: sleep 1h 
